using System;
using System.Collections.Generic;
using System.Linq;
using Domain.Backend.Tasks.Whois;

namespace Domain.Backend.Utilities.Whois;

public sealed class StaticWhoisServerResolver : IWhoisServerResolver
{
    private static readonly IReadOnlyDictionary<string, string> Servers = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["app"] = "whois.nic.google",
        ["biz"] = "whois.biz",
        ["com"] = "whois.verisign-grs.com",
        ["dev"] = "whois.nic.google",
        ["info"] = "whois.afilias.net",
        ["net"] = "whois.verisign-grs.com",
        ["one"] = "whois.nic.one",
        ["org"] = "whois.pir.org",
        ["top"] = "whois.nic.top",
        ["xyz"] = "whois.nic.xyz",
        
        ["ac"] = "whois.nic.ac",
        ["ad"] = "whois.nic.ad",
        ["ae"] = "whois.aeda.net.ae",
        ["af"] = "whois.nic.af",
        ["ag"] = "whois.nic.ag",
        ["ai"] = "whois.nic.ai",
        ["am"] = "whois.amnic.net",
        ["ar"] = "whois.nic.ar",
        ["as"] = "whois.nic.as",
        ["at"] = "whois.nic.at",
        ["au"] = "whois.auda.org.au",
        ["aw"] = "whois.nic.aw",
        ["ax"] = "whois.ax",
        ["az"] = "whois.az",
        ["ba"] = "whois.nic.ba",
        ["be"] = "whois.dns.be",
        ["bg"] = "whois.register.bg",
        ["bh"] = "whois.nic.bh",
        ["bi"] = "whois1.nic.bi",
        ["bj"] = "whois.nic.bj",
        ["bm"] = "whois.nic.bm",
        ["bo"] = "whois.nic.bo",
        ["br"] = "whois.registro.br",
        ["bt"] = "whois.nic.bt",
        ["bw"] = "whois.nic.net.bw",
        ["by"] = "whois.cctld.by",
        ["bz"] = "whois.afilias-grs.info",
        ["ca"] = "whois.cira.ca",
        ["cc"] = "ccwhois.verisign-grs.com",
        ["cd"] = "whois.nic.cd",
        ["ch"] = "whois.nic.ch",
        ["ci"] = "whois.nic.ci",
        ["ck"] = "whois.nic.ck",
        ["cl"] = "whois.nic.cl",
        ["cm"] = "whois.netcom.cm",
        ["cn"] = "whois.cnnic.cn",
        ["co"] = "whois.nic.co",
        ["com.cn"] = "whois.cnnic.cn",
        ["cr"] = "whois.nic.cr",
        ["cu"] = "whois.nic.cu",
        ["cx"] = "whois.nic.cx",
        ["cy"] = "whois.nic.cy",
        ["cz"] = "whois.nic.cz",
        ["de"] = "whois.denic.de",
        ["dk"] = "whois.dk-hostmaster.dk",
        ["dm"] = "whois.dmdomains.dm",
        ["do"] = "whois.nic.do",
        ["dz"] = "whois.nic.dz",
        ["ec"] = "whois.nic.ec",
        ["ee"] = "whois.tld.ee",
        ["es"] = "whois.nic.es",
        ["eu"] = "whois.eu",
        ["fi"] = "whois.fi",
        ["fo"] = "whois.nic.fo",
        ["fr"] = "whois.nic.fr",
        ["ga"] = "whois.nic.ga",
        ["gd"] = "whois.nic.gd",
        ["ge"] = "whois.nic.ge",
        ["gf"] = "whois.mediaserv.net",
        ["gg"] = "whois.gg",
        ["gi"] = "whois2.afilias-grs.net",
        ["gl"] = "whois.nic.gl",
        ["gm"] = "whois.nic.gm",
        ["gp"] = "whois.nic.gp",
        ["gr"] = "whois.ics.forth.gr",
        ["gs"] = "whois.nic.gs",
        ["gy"] = "whois.registry.gy",
        ["hk"] = "whois.hkirc.hk",
        ["hn"] = "whois.nic.hn",
        ["hr"] = "whois.dns.hr",
        ["ht"] = "whois.nic.ht",
        ["hu"] = "whois.nic.hu",
        ["id"] = "whois.id",
        ["ie"] = "whois.weare.ie",
        ["il"] = "whois.isoc.org.il",
        ["im"] = "whois.nic.im",
        ["in"] = "whois.registry.in",
        ["io"] = "whois.nic.io",
        ["ir"] = "whois.nic.ir",
        ["is"] = "whois.isnic.is",
        ["it"] = "whois.nic.it",
        ["je"] = "whois.je",
        ["jp"] = "whois.jprs.jp",
        ["ke"] = "whois.kenic.or.ke",
        ["kg"] = "whois.kg",
        ["ki"] = "whois.nic.ki",
        ["kr"] = "whois.kr",
        ["kz"] = "whois.nic.kz",
        ["la"] = "whois.nic.la",
        ["li"] = "whois.nic.li",
        ["lt"] = "whois.domreg.lt",
        ["lu"] = "whois.dns.lu",
        ["lv"] = "whois.nic.lv",
        ["ly"] = "whois.nic.ly",
        ["ma"] = "whois.registre.ma",
        ["mc"] = "whois.ripe.net",
        ["md"] = "whois.nic.md",
        ["me"] = "whois.nic.me",
        ["mg"] = "whois.nic.mg",
        ["mk"] = "whois.marnet.mk",
        ["ml"] = "whois.nic.ml",
        ["mn"] = "whois.nic.mn",
        ["mo"] = "whois.monic.mo",
        ["ms"] = "whois.nic.ms",
        ["mu"] = "whois.nic.mu",
        ["mx"] = "whois.mx",
        ["my"] = "whois.mynic.my",
        ["mz"] = "whois.nic.mz",
        ["na"] = "whois.na-nic.com.na",
        ["nc"] = "whois.nc",
        ["net.cn"] = "whois.cnnic.cn",
        ["nf"] = "whois.nic.nf",
        ["ng"] = "whois.nic.net.ng",
        ["nl"] = "whois.domain-registry.nl",
        ["no"] = "whois.norid.no",
        ["nr"] = "whois.nic.nr",
        ["nu"] = "whois.iis.nu",
        ["nz"] = "whois.irs.net.nz",
        ["om"] = "whois.registry.om",
        ["org.cn"] = "whois.cnnic.cn",
        ["pe"] = "kero.yachay.pe",
        ["pf"] = "whois.registry.pf",
        ["pl"] = "whois.dns.pl",
        ["pm"] = "whois.nic.pm",
        ["pr"] = "whois.afilias-srs.net",
        ["pt"] = "whois.dns.pt",
        ["pw"] = "whois.nic.pw",
        ["qa"] = "whois.registry.qa",
        ["re"] = "whois.nic.re",
        ["ro"] = "whois.rotld.ro",
        ["rs"] = "whois.rnids.rs",
        ["ru"] = "whois.tcinet.ru",
        ["rw"] = "whois.ricta.org.rw",
        ["sa"] = "whois.nic.net.sa",
        ["sb"] = "whois.nic.net.sb",
        ["sc"] = "whois2.afilias-grs.net",
        ["se"] = "whois.iis.se",
        ["sg"] = "whois.sgnic.sg",
        ["sh"] = "whois.nic.sh",
        ["si"] = "whois.register.si",
        ["sk"] = "whois.sk-nic.sk",
        ["sl"] = "whois.nic.sl",
        ["sm"] = "whois.nic.sm",
        ["sn"] = "whois.nic.sn",
        ["so"] = "whois.nic.so",
        ["st"] = "whois.nic.st",
        ["su"] = "whois.tcinet.ru",
        ["sx"] = "whois.sx",
        ["sy"] = "whois.tld.sy",
        ["tc"] = "whois.nic.tc",
        ["tf"] = "whois.nic.tf",
        ["th"] = "whois.thnic.co.th",
        ["tl"] = "whois.nic.tl",
        ["tm"] = "whois.nic.tm",
        ["tn"] = "whois.ati.tn",
        ["to"] = "whois.tonic.to",
        ["tr"] = "whois.nic.tr",
        ["tv"] = "tvwhois.verisign-grs.com",
        ["tw"] = "whois.twnic.net.tw",
        ["tz"] = "whois.tznic.or.tz",
        ["ua"] = "whois.ua",
        ["ug"] = "whois.co.ug",
        ["uk"] = "whois.nic.uk",
        ["us"] = "whois.nic.us",
        ["uy"] = "whois.nic.org.uy",
        ["uz"] = "whois.cctld.uz",
        ["vc"] = "whois2.afilias-grs.net",
        ["ve"] = "whois.nic.ve",
        ["vg"] = "whois.nic.vg",
        ["vu"] = "vunic.vu",
        ["wf"] = "whois.nic.wf",
        ["ws"] = "whois.website.ws",
        ["yt"] = "whois.nic.yt",
        ["zm"] = "whois.nic.zm"
    };

    private static readonly IReadOnlySet<string> GenericTlds = new HashSet<string>(StringComparer.Ordinal)
    {
        "app",
        "biz",
        "com",
        "dev",
        "info",
        "net",
        "one",
        "org",
        "top",
        "xyz"
    };

    public string? ResolveServer(string tld)
    {
        return Servers.TryGetValue(tld, out var server) ? server : null;
    }

    public IReadOnlyList<string> GetSupportedTlds()
    {
        return Servers.Keys.Order(StringComparer.Ordinal).ToArray();
    }

    public IReadOnlyList<SupportedTldInfo> GetSupportedTldInfos()
    {
        return Servers.Keys
            .Order(StringComparer.Ordinal)
            .Select(static tld => new SupportedTldInfo(tld, GenericTlds.Contains(tld) ? "generic" : "country-code"))
            .ToArray();
    }
}
